name: Terraform Plan

on:
  push:
    branches: [ main ]
    paths:
      - "terraform/week7/**"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    name: Plan VPC Infrastructure
    defaults:
      run:
        working-directory: terraform/week7

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to GCP via OIDC
        uses: google-github-actions/auth@v2
        with:
          # Directly using the values here ignores the broken Variables tab
          workload_identity_provider: 'projects/126083374521/locations/global/workloadIdentityPools/cis410-pool/providers/github-provider'
          service_account: 'cis410-deploy-sa@cis410-ehsan.iam.gserviceaccount.com'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -no-color
        env:
          TF_VAR_project_id: ${{ vars.TF_VAR_PROJECT_ID }}
          TF_VAR_my_ip_cidr: ${{ vars.TF_VAR_MY_IP_CIDR }}